import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    // {
    //   name: "Remington Standard",
    //   slug: "typewriter-remington-standard",
    //   category: "Typewriters",
    //   subcategory: "",
    //   image: "/images/vintage/typewriters/typewriter1.jpg",
    //   price: 70,
    //   brand: "Remington",
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic typewriter...",
    // },
    // {
    //   name: "Underwood Standard",
    //   slug: "typewriter-uderwood-standard",
    //   category: "Typewriters",
    //   subcategory: "",
    //   image: "/images/vintage/typewriters/typewriter2.jpg",
    //   price: 80,
    //   brand: "Underwood",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic portable typewriter...",
    // },
    // {
    //   name: "Telephone No.1",
    //   slug: "telephone-1",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone1.jpg",
    //   price: 90,
    //   brand: "No.1",
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Telephone No.2",
    //   slug: "telephone-2",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone2.jpg",
    //   price: 100,
    //   brand: "No.2",
    //   rating: 4.0,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Telephone No.3",
    //   slug: "telephone-3",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone3.jpg",
    //   price: 80,
    //   brand: "No.3",
    //   rating: 4.8,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Telephone No.4",
    //   slug: "telephone-4",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone4.jpg",
    //   price: 200,
    //   brand: "No.4",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Telephone No.5",
    //   slug: "telephone-5",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone5.jpg",
    //   price: 150,
    //   brand: "No.5",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Telephone No.6",
    //   slug: "telephone-6",
    //   category: "Telephones",
    //   subcategory: "",
    //   image: "/images/vintage/telephones/telephone6.jpg",
    //   price: 250,
    //   brand: "No.6",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telephone...",
    // },
    // {
    //   name: "Magnifying Glass",
    //   slug: "magnifying-glass-1",
    //   category: "Spy Glasses",
    //   subcategory: "Magnifying Glasses",
    //   image: "/images/vintage/spyglasses/magnifying_glass1.jpg",
    //   price: 50,
    //   brand: "Magnifying Glasses Co.",
    //   rating: 3.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic magnifying glass...",
    // },
    // {
    //   name: "Telescope",
    //   slug: "telescope-1",
    //   category: "Spy Glasses",
    //   subcategory: "Telescopes",
    //   image: "/images/vintage/spyglasses/telescope1.jpg",
    //   price: 550,
    //   brand: "Telescopes Co.",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic telesope...",
    // },
    // {
    //   name: "Radio Invicta",
    //   slug: "radio-invicta-1",
    //   category: "RTV",
    //   subcategory: "Radios",
    //   image: "/images/vintage/RTV_equipment/radio1.jpg",
    //   price: 350,
    //   brand: "Invicta",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic radio...",
    // },
    // {
    //   name: "Radio Philetta",
    //   slug: "radio-philetta-1",
    //   category: "RTV",
    //   subcategory: "Radios",
    //   image: "/images/vintage/RTV_equipment/radio2.jpg",
    //   price: 850,
    //   brand: "Philips",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic radio...",
    // },
    // {
    //   name: "Jukebox",
    //   slug: "jukebox-1",
    //   category: "RTV",
    //   subcategory: "Speekers",
    //   image: "/images/vintage/RTV_equipment/speeker1.jpg",
    //   price: 1050,
    //   brand: "Jukebox Co.Ltd",
    //   rating: 4.7,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic jukebox...",
    // },
    // {
    //   name: "World Globe No.1",
    //   slug: "globe-1",
    //   category: "Geography",
    //   subcategory: "Globes",
    //   image: "/images/vintage/maps/globe1.jpg",
    //   price: 120,
    //   brand: "Globe Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic world globe...",
    // },
    // {
    //   name: "World Globe No.2",
    //   slug: "globe-2",
    //   category: "Geography",
    //   subcategory: "Globes",
    //   image: "/images/vintage/maps/globe2.jpg",
    //   price: 20,
    //   brand: "Globe Co.Ltd",
    //   rating: 3.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic world globe...",
    // },
    // {
    //   name: "World Map No.1",
    //   slug: "map-1",
    //   category: "Geography",
    //   subcategory: "Maps",
    //   image: "/images/vintage/maps/map1.jpg",
    //   price: 50,
    //   brand: "Maps Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic world map...",
    // },
    // {
    //   name: "World Map No.2",
    //   slug: "map-2",
    //   category: "Geography",
    //   subcategory: "Maps",
    //   image: "/images/vintage/maps/map2.jpg",
    //   price: 40,
    //   brand: "Maps Co.Ltd",
    //   rating: 4.1,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic world map...",
    // },
    // {
    //   name: "World Map No.3",
    //   slug: "map-3",
    //   category: "Geography",
    //   subcategory: "Maps",
    //   image: "/images/vintage/maps/map3.jpg",
    //   price: 90,
    //   brand: "Maps Co.Ltd",
    //   rating: 4.8,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic world map...",
    // },
    // {
    //   name: "Lantern No.1",
    //   slug: "lantern-1",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern1.jpg",
    //   price: 50,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Lantern No.2",
    //   slug: "lantern-2",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern2.jpg",
    //   price: 20,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Lantern No.3",
    //   slug: "lantern-3",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern3.jpg",
    //   price: 30,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Lantern No.4",
    //   slug: "lantern-4",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern4.jpg",
    //   price: 70,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Lantern No.5",
    //   slug: "lantern-5",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern5.jpg",
    //   price: 10,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Lantern No.6",
    //   slug: "lantern-6",
    //   category: "Lights",
    //   subcategory: "Lanterns",
    //   image: "/images/vintage/lights/lantern6.jpg",
    //   price: 80,
    //   brand: "Lights Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic lamp...",
    // },
    // {
    //   name: "Coffee Mill No.1",
    //   slug: "coffee-mill-1",
    //   category: "HA",
    //   subcategory: "Mills",
    //   image: "/images/vintage/household_appliances/coffee_mill1.jpg",
    //   price: 40,
    //   brand: "Mills Co.Ltd",
    //   rating: 4.3,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic coffee mill...",
    // },
    // {
    //   name: "Coffee Mill No.2",
    //   slug: "coffee-mill-2",
    //   category: "HA",
    //   subcategory: "Mills",
    //   image: "/images/vintage/household_appliances/coffee_mill2.jpg",
    //   price: 30,
    //   brand: "Mills Co.Ltd",
    //   rating: 4.4,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic coffee mill...",
    // },
    // {
    //   name: "Coffee Mill No.3",
    //   slug: "coffee-mill-3",
    //   category: "HA",
    //   subcategory: "Mills",
    //   image: "/images/vintage/household_appliances/coffee_mill3.jpg",
    //   price: 35,
    //   brand: "Mills Co.Ltd",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic coffee mill...",
    // },
    // {
    //   name: "Old Mill No.1",
    //   slug: "old-mill-1",
    //   category: "HA",
    //   subcategory: "Mills",
    //   image: "/images/vintage/household_appliances/old_mill1.jpg",
    //   price: 40,
    //   brand: "Mills Co.Ltd",
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic mill...",
    // },
    // {
    //   name: "Old Mill No.2",
    //   slug: "old-mill-2",
    //   category: "HA",
    //   subcategory: "Mills",
    //   image: "/images/vintage/household_appliances/old_mill2.jpg",
    //   price: 60,
    //   brand: "Mills Co.Ltd",
    //   rating: 4.6,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic mill...",
    // },
    // {
    //   name: "Coffee Pot No.1",
    //   slug: "coffee-pot-1",
    //   category: "HA",
    //   subcategory: "Pots",
    //   image: "/images/vintage/household_appliances/coffee_pot1.jpg",
    //   price: 100,
    //   brand: "Pots Co.Ltd",
    //   rating: 4.8,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic coffee pot...",
    // },
    // {
    //   name: "Coffee Pot No.2",
    //   slug: "coffee-pot-2",
    //   category: "HA",
    //   subcategory: "Pots",
    //   image: "/images/vintage/household_appliances/coffee_pot2.jpg",
    //   price: 80,
    //   brand: "Pots Co.Ltd",
    //   rating: 4.7,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic coffee pot...",
    // },
    // {
    //   name: "Tea Pot No.1",
    //   slug: "tea-pot-1",
    //   category: "HA",
    //   subcategory: "Pots",
    //   image: "/images/vintage/household_appliances/tea_pot1.jpg",
    //   price: 115,
    //   brand: "Pots Co.Ltd",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic tea pot...",
    // },
    // {
    //   name: "Flat Iron No.1",
    //   slug: "flat-iron-1",
    //   category: "HA",
    //   subcategory: "Irons",
    //   image: "/images/vintage/household_appliances/flat_iron1.jpg",
    //   price: 34,
    //   brand: "Irons Co.Ltd",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic iron...",
    // },
    // {
    //   name: "Flat Iron No.2",
    //   slug: "flat-iron-2",
    //   category: "HA",
    //   subcategory: "Irons",
    //   image: "/images/vintage/household_appliances/flat_iron2.jpg",
    //   price: 37,
    //   brand: "Irons Co.Ltd",
    //   rating: 4.1,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic iron...",
    // },
    // {
    //   name: "Clock No.1",
    //   slug: "clock-1",
    //   category: "Clocks",
    //   subcategory: "Grandfather Clocks",
    //   image: "/images/vintage/clocks/clock1.jpg",
    //   price: 450,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Clock No.2",
    //   slug: "clock-2",
    //   category: "Clocks",
    //   subcategory: "",
    //   image: "/images/vintage/clocks/clock2.jpg",
    //   price: 350,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Clock No.3",
    //   slug: "clock-3",
    //   category: "Clocks",
    //   subcategory: "",
    //   image: "/images/vintage/clocks/clock3.jpg",
    //   price: 250,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.7,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Wall Clock No.1",
    //   slug: "wall-clock-1",
    //   category: "Clocks",
    //   subcategory: "Wall Clocks",
    //   image: "/images/vintage/clocks/wall_clock1.jpg",
    //   price: 290,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.8,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Wall Clock No.2",
    //   slug: "wall-clock-2",
    //   category: "Clocks",
    //   subcategory: "Wall Clocks",
    //   image: "/images/vintage/clocks/wall_clock2.jpg",
    //   price: 430,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Wall Clock No.3",
    //   slug: "wall-clock-3",
    //   category: "Clocks",
    //   subcategory: "Wall Clocks",
    //   image: "/images/vintage/clocks/wall_clock3.jpg",
    //   price: 610,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.4,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Wall Clock No.4",
    //   slug: "wall-clock-4",
    //   category: "Clocks",
    //   subcategory: "Wall Clocks",
    //   image: "/images/vintage/clocks/wall_clock4.jpg",
    //   price: 444,
    //   brand: "Clocks Co.Ltd",
    //   rating: 5.0,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic clock...",
    // },
    // {
    //   name: "Watch No.1",
    //   slug: "watch-1",
    //   category: "Clocks",
    //   subcategory: "Watches",
    //   image: "/images/vintage/clocks/watch1.jpg",
    //   price: 505,
    //   brand: "Clocks Co.Ltd",
    //   rating: 5.0,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic watch...",
    // },
    // {
    //   name: "Watch No.2",
    //   slug: "watch-2",
    //   category: "Clocks",
    //   subcategory: "Watches",
    //   image: "/images/vintage/clocks/watch2.jpg",
    //   price: 390,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.8,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic watch...",
    // },
    // {
    //   name: "Watch No.3",
    //   slug: "watch-3",
    //   category: "Clocks",
    //   subcategory: "Watches",
    //   image: "/images/vintage/clocks/watch3.jpg",
    //   price: 450,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.9,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic watch...",
    // },
    // {
    //   name: "Watch No.4",
    //   slug: "watch-4",
    //   category: "Clocks",
    //   subcategory: "Watches",
    //   image: "/images/vintage/clocks/watch4.jpg",
    //   price: 950,
    //   brand: "Clocks Co.Ltd",
    //   rating: 5.0,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic watch...",
    // },
    // {
    //   name: "Watch No.5",
    //   slug: "watch-5",
    //   category: "Clocks",
    //   subcategory: "Watches",
    //   image: "/images/vintage/clocks/watch5.jpg",
    //   price: 450,
    //   brand: "Clocks Co.Ltd",
    //   rating: 4.7,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: "This is a fantastic watch...",
    // },
    {
      name: "Camera No.1",
      slug: "camera-1",
      category: "Cameras",
      subcategory: "",
      image: "/images/vintage/cameras/camera1.jpg",
      price: 450,
      brand: "Cameras Co.Ltd",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic camera...",
    },
    {
      name: "Camera No.2",
      slug: "camera-2",
      category: "Cameras",
      subcategory: "",
      image: "/images/vintage/cameras/camera2.jpg",
      price: 550,
      brand: "Cameras Co.Ltd",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic camera...",
    },
    {
      name: "Camera No.3",
      slug: "camera-3",
      category: "Cameras",
      subcategory: "",
      image: "/images/vintage/cameras/camera3.jpg",
      price: 370,
      brand: "Cameras Co.Ltd",
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic camera...",
    },
    {
      name: "Camera No.4",
      slug: "camera-4",
      category: "Cameras",
      subcategory: "",
      image: "/images/vintage/cameras/camera4.jpg",
      price: 740,
      brand: "Cameras Co.Ltd",
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic camera...",
    },
    {
      name: "Camera No.5",
      slug: "camera-5",
      category: "Cameras",
      subcategory: "",
      image: "/images/vintage/cameras/camera5.jpg",
      price: 810,
      brand: "Cameras Co.Ltd",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic camera...",
    },
    {
      name: "Bicycle No.1",
      slug: "bicycle-1",
      category: "Bicycles",
      subcategory: "",
      image: "/images/vintage/bicycles/bicycle1.jpg",
      price: 900,
      brand: "Bicycles Co.Ltd",
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic bicycle...",
    },
    {
      name: "Bicycle No.2",
      slug: "bicycle-2",
      category: "Bicycles",
      subcategory: "",
      image: "/images/vintage/bicycles/bicycle2.jpg",
      price: 800,
      brand: "Bicycles Co.Ltd",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic bicycle...",
    },
    {
      name: "Bicycle No.3",
      slug: "bicycle-3",
      category: "Bicycles",
      subcategory: "",
      image: "/images/vintage/bicycles/bicycle3.jpg",
      price: 900,
      brand: "Bicycles Co.Ltd",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic bicycle...",
    },
    {
      name: "Bicycle No.4",
      slug: "bicycle-4",
      category: "Bicycles",
      subcategory: "",
      image: "/images/vintage/bicycles/bicycle4.jpg",
      price: 700,
      brand: "Bicycles Co.Ltd",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic bicycle...",
    },
    {
      name: "Bicycle No.5",
      slug: "bicycle-5",
      category: "Bicycles",
      subcategory: "",
      image: "/images/vintage/bicycles/bicycle5.jpg",
      price: 950,
      brand: "Bicycles Co.Ltd",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "This is a fantastic bicycle...",
    },
    {
      name: "Clogs No.1",
      slug: "clogs-1",
      category: "Clogs",
      subcategory: "",
      image: "/images/vintage/clogs/clogs1.jpg",
      price: 100,
      brand: "Clogs Co.Ltd",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "This are a fantastic clogs...",
    },
    {
      name: "Clogs No.2",
      slug: "clogs-2",
      category: "Clogs",
      subcategory: "",
      image: "/images/vintage/clogs/clogs2.jpg",
      price: 200,
      brand: "Clogs Co.Ltd",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "This are a fantastic clogs...",
    },
    {
      name: "Clogs No.3",
      slug: "clogs-3",
      category: "Clogs",
      subcategory: "",
      image: "/images/vintage/clogs/clogs3.jpg",
      price: 150,
      brand: "Clogs Co.Ltd",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "This are a fantastic clogs...",
    },
    {
      name: "Clogs No.4",
      slug: "clogs-4",
      category: "Clogs",
      subcategory: "",
      image: "/images/vintage/clogs/clogs4.jpg",
      price: 180,
      brand: "Clogs Co.Ltd",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "This are a fantastic clogs...",
    },
  ],
};

export default data;
